// Copyright 2019 The Goma Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "elf_util.h"

#include <string>
#include <vector>

#include "absl/strings/string_view.h"
#include "gtest/gtest.h"

namespace devtools_goma {

TEST(ElfUtilTest, ParseLdSoConf) {
  static constexpr absl::string_view kExampleContent =
      "# ld.so.conf autogenerated by env-update; make all changes to\n"
      "# contents of /etc/env.d directory\n"
      "/lib64\n"
      "/usr/lib64\n"
      "/usr/local/lib64\n"
      "/lib32\n"
      "/usr/lib32\n"
      "/usr/local/lib32\n"
      "/lib\n"
      "/usr/lib\n"
      "/usr/local/lib\n"
      "include ld.so.conf.d/*.conf\n"
      "/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.x/32\n"
      "/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.x\n"
      "/usr/x86_64-pc-linux-gnu/lib\n";
  std::vector<std::string> result = ParseLdSoConf(kExampleContent);
  std::vector<std::string> expected_result = {
      "/lib64",
      "/usr/lib64",
      "/usr/local/lib64",
      "/lib32",
      "/usr/lib32",
      "/usr/local/lib32",
      "/lib",
      "/usr/lib",
      "/usr/local/lib",
      "/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.x/32",
      "/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.x",
      "/usr/x86_64-pc-linux-gnu/lib",
  };
  EXPECT_EQ(expected_result, result);
}

}  // namespace devtools_goma
